# 8/09/2022

# Numpy


# Muallif: Farrux Sotivoldiyev

# Bool bilan ishlovchi operatsiyalar

* `& - va` - Ikalasi ham True bo'lgandagina True aks holda False
* `| - yoki` - Ikalasidan biri yoki ikalasi ham True bo'lgandagina True aks holda False
* `^ - xor` - Ikalasi ham bir xil bool(True-True or False-False) bo'lgandagina False aks holda True
* `~ - nor` - Inkor vazifasini bajaradi
* `>> - o'ngga surish` - o'ngga n suriladi va sonimiz manfiy bolsa orqadan shuncha 1lar qo'shiladi,musbat bo'lsa 0
* `<< - chapga surish` - chapga n suriladi va orqadan 0 lar qo'shiladi

**`Numpy kutubxonasini chaqirib olamiz`**

In [2]:
import numpy as np

In [3]:
np_15 = np.array([True,False,True,False])
np_16 = np.array([False,False,True,True])

In [4]:
np_15 & np_16

array([False, False,  True, False])

In [5]:
np_15 | np_16

array([ True, False,  True,  True])

In [6]:
np_15 ^ np_16

array([ True, False, False,  True])

In [7]:
~ np_15

array([False,  True, False,  True])

In [8]:
np_15 = np.array([1,2,3,4]).reshape(2,2)
np_16 = np.array([3,4,2,1]).reshape(2,2)
print(np_15)
print()
print(np_16)

[[1 2]
 [3 4]]

[[3 4]
 [2 1]]


* `bu amallarni sonlar ustida bajarish uchun oldin ikkilikka o'tqaziladi va belgi(&|^~) bo'yicha amallar bajariladi.`

In [9]:
np_15 & np_16 

array([[1, 0],
       [2, 0]])

In [10]:
np_15 | np_16 

array([[3, 6],
       [3, 5]])

In [11]:
np_15 ^ np_16 

array([[2, 6],
       [1, 5]])

In [12]:
~ np_16 

array([[-4, -5],
       [-3, -2]])

**` Surish:`**
* 1.o'ng tomonga 2 surishda o'ng tomondan 2ta xonasini olib tashlanadi va va chap tarafdan shuncha 0 lar qo'shiladi 
* 2.chap tomonga 2 surishda chap tomondan 2ta xonasini olib tashlanadi va va ong tarafdan shuncha 0 lar qo'shiladi

**`Istisno holat:`**
* `Manfiy sonlarni o'ng tomonga surishda orqqasidan 1 lar qo'shiladi,qolgan xollarda har doim 0 lar qo'shiladi` 

In [13]:
np_16 >> 2

array([[0, 1],
       [0, 0]], dtype=int32)

In [14]:
np_16 << 3

array([[24, 32],
       [16,  8]], dtype=int32)

In [15]:
(~ np_16) >> 2 

array([[-1, -2],
       [-1, -1]], dtype=int32)

# Where mantiqiy funksiyasi.
* np.where(condition,x,y)

* Where ning ishlashi - u conditiondan qaytgan True va False ga qarab ishlaydi.Agar True qaytsa birinchi yozilganini False qaytsa ikkinchi yozilganidan mos indexdagi qiymatni oladi   

* Faqat condition kiritilsa index qaytaradi

* Conditionda True va False qiymatga ega list hz lar bo'ladi ya'ni list shape np_17 va np_18 ni shape lariga teng bo'lishi kerak

* Bitta True yoki bitta False bo'lsa unga mos qiymatni hammasini oladi

**`1D array bilan ishlash`**

In [17]:
np_17 = np.array([1,2,3,4])
np_18 = np.array([3,4,2,1])

In [18]:
np.where(np_17>np_18,np_17,np_18)

array([3, 4, 3, 4])

In [19]:
np.where(np_17>np_18)

(array([2, 3], dtype=int64),)

In [20]:
np_15 = np.array([True,False,True,False])
np_17 = np.array([1,2,3,4])
np_18 = np.array([3,4,2,1])

In [21]:
np.where(np_15,np_17,np_18)

array([1, 4, 3, 1])

* Agar conditionga bitta bool yozsak shu qiymatga qarab np_17 yoki np_18 ni barcha elementini oladi

In [22]:
np.where(True,np_17,np_18)

array([1, 2, 3, 4])

In [23]:
np.where(False,np_17,np_18)

array([3, 4, 2, 1])

* Ichidagi elementi str bo'lsa ularni solishtirishda ASCII jadvalidagi o'rni bo'yicha solishtiriladi va qaytgan bool ga qarab np_17 yoki np_18 dan o'sha indexdagi elementini oladi

In [24]:
np_17 = np.array(['salom','iltimos','gilos'])
np_18 = np.array(['hello','valaykum','qalesan'])

In [25]:
np.where(np_17>np_18,np_17,np_18)

array(['salom', 'valaykum', 'qalesan'], dtype='<U8')

**`2D array bilan ishlash`**

In [26]:
np_17 = np.array([2,3,0,9,4,8]).reshape(2,3)
np_18 = np.array([1,6,11,10,5,7]).reshape(2,3)
print(np_17)
print("--------------")
print(np_18)

[[2 3 0]
 [9 4 8]]
--------------
[[ 1  6 11]
 [10  5  7]]


In [27]:
np.where((np_17//np_18)>1,np_17+1,np_18-2)

array([[3, 4, 9],
       [8, 3, 5]])

**`3D array bilan ishlash`**

In [28]:
np_17 = np.arange(0,27).reshape(3,3,3)
np_18 = np.arange(28,55).reshape(3,3,3)
print(np_17)
print("--------------")
print(np_18)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
--------------
[[[28 29 30]
  [31 32 33]
  [34 35 36]]

 [[37 38 39]
  [40 41 42]
  [43 44 45]]

 [[46 47 48]
  [49 50 51]
  [52 53 54]]]


In [29]:
np.where(np_17>np_18,np_17,np_18)

array([[[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[37, 38, 39],
        [40, 41, 42],
        [43, 44, 45]],

       [[46, 47, 48],
        [49, 50, 51],
        [52, 53, 54]]])

**`Ozimiz class yaratib where da qo'llash`**

In [30]:
class Math:
    def __init__(self,massiv):
        self.massiv = massiv
        
    def __lt__(self,other):
        return self.massiv < other.massiv
    
    def __eq__(self,other):
        return self.massiv == other.massiv
    
    def __le__(self,other):
        return self.massiv <= other.massiv
    
    def __add__(self,other):
        return self.massiv + other.massiv

In [31]:
x = Math(np_17)
y = Math(np_18)

In [32]:
np.where(x>y,np_17,np_18)

array([[[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[37, 38, 39],
        [40, 41, 42],
        [43, 44, 45]],

       [[46, 47, 48],
        [49, 50, 51],
        [52, 53, 54]]])

In [33]:
np.where((x+y)%2==0,np_17+1,np_18)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])