# 8/09/2022

# Numpy


# Muallif: Farrux Sotivoldiyev

# Fayllar bilan ishlash (Numpy)
* `np.save` - faqat 1 ta arrayni save qiladi
* `np.savetxt` - txt fayl qilib saqlaydi
* `np.savez` - 2 va undan ortig'ini save qiladi,zip ga o'xshash
* `np.savez_compressed` - savez ni compress varianti
* `np.load`  - malumotni o'qiydi
* `np.loadtxt` - faqat txt faylidagi malumotlatni o'qiydi
* `.files` - fileni ichida qanday o'zgaruvchilar borligini bilish

**`Numpy kutubxonasini chaqirib olamiz`**

In [2]:
import numpy as np

**`np.save`** - npy ko'rinishida saqlaydi . Faqat bitta data saqlash mumkin 

In [7]:
array = np.arange(5)
np.save("data",array)

In [8]:
array1 = np.arange(5)
np.save("data1.npy",array1)

**`np.savetxt`**

In [39]:
np.savetxt("file_txt",array3)

**`np.savez`** - npz korinishida saqlaydi.Ikki va undan ortiq data saqlash ham mumkin 

In [9]:
array3 = np.arange(10)
np.savez("data3.npz",array3,array1)

**`np.savez_compressed`** - npz korinishida saqlaydi.Bu ham hohlagancha malumot saqlaydi va compress qilib qoyadi

In [10]:
array3 = np.arange(10)
np.savez_compressed("data4.npz",array3,array1)

**`np.load`** - fayldagi malumotlatni o'qiydi

In [11]:
np.load("data.npy")

array([0, 1, 2, 3, 4])

In [15]:
arrays = np.load("data4.npz") # ichida 2 va undan ortiq o'zgarucvhida ma'lumot bor bo'lsa obyekt qaytaradi
arrays

In [22]:
arrays.files # ichidagi ma'lumotlarni nomini chiqaradi . Default holatda uzi qo'yadi fayl nomini

['arr_0', 'arr_1']

In [23]:
arrays['arr_0'] # shunday qilib qayta o'qib olinadi

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arrays['arr_1'] # shunday qilib qayta o'qib olinadi

array([0, 1, 2, 3, 4])

**`np.loadtxt`** - faqat txt faylidagi malumotlatni o'qiydi

In [41]:
np.loadtxt("file_txt")

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

**`np.savez`** - har bitta data ga alohidadan nom berib saqlash

In [25]:
array_1 = np.array([1,2,3,4,5,6,7])
array_2 = np.array([11,21,31,41,51,16,71])

In [26]:
np.savez("data5",a=array_1,b=array_2)

In [28]:
arrays = np.load("data5.npz")
arrays

In [30]:
arrays.files # ko'rishingiz mumkin biz bergan nom bo'yicha saqlangan ekan

['a', 'b']

In [31]:
arrays["a"]

array([1, 2, 3, 4, 5, 6, 7])

In [32]:
arrays["b"]

array([11, 21, 31, 41, 51, 16, 71])