# 8/09/2022

# Numpy


# Muallif: Farrux Sotivoldiyev

# Index and Slice

**`Numpy kutubxonasini chaqirib olamiz`**

In [1]:
import numpy as np

In [18]:
np_1d = np.array([1,2,3,4])
np_2d = np.arange(12).reshape(3,4)
np_3d = (np.arange(18).reshape(3,2,3),1)

In [96]:
np_1d

array([1, 2, 3, 4])

In [97]:
np_1d[1]

2

In [102]:
np_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [105]:
np_2d[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [26]:
np_3d[0]

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [27]:
np_3d[0][2:]

array([[[12, 13, 14],
        [15, 16, 17]]])

In [107]:
np_3d[1,:,1:]

array([[ 7,  8],
       [10, 11]])

In [108]:
np_3d[2,:,1:]

array([[13, 14],
       [16, 17]])

**` Copy - slice bilan copy qilganimizda ID lari bir xil bo'lib qoladi.Bu tafsiya qilinmaydi deepcopy yoki asarray yordamida copy qilish kerak.`**

In [1]:
import numpy as np
x = np.random.randint(1,9,size=(10,10))
x[2:8,2:8]=0
x

array([[2, 7, 2, 6, 7, 2, 2, 7, 3, 3],
       [4, 3, 8, 1, 1, 4, 8, 2, 5, 6],
       [8, 6, 0, 0, 0, 0, 0, 0, 5, 2],
       [1, 6, 0, 0, 0, 0, 0, 0, 7, 7],
       [3, 1, 0, 0, 0, 0, 0, 0, 7, 7],
       [6, 1, 0, 0, 0, 0, 0, 0, 5, 1],
       [4, 2, 0, 0, 0, 0, 0, 0, 3, 6],
       [6, 8, 0, 0, 0, 0, 0, 0, 5, 3],
       [6, 5, 2, 2, 3, 8, 3, 1, 4, 8],
       [6, 6, 4, 7, 2, 6, 5, 7, 3, 5]])