# Linear algebra
* np.linalg.det() - determinant topish
* np.linalg.inv() - teskarisini topish

**`Numpy kutubxonasini chaqirib olamiz`**

In [1]:
import numpy as np

**`np.linalg.det`**

In [2]:
np_0 = np.random.randint(1,5,size=(4,4))
np_0

array([[3, 1, 1, 3],
       [3, 2, 3, 3],
       [4, 2, 3, 3],
       [1, 1, 2, 3]])

In [3]:
np.linalg.det(np_0)

3.0000000000000004

**`np.linalg.inv`**

In [4]:
inverse = np.linalg.inv(np_0)
inverse

array([[ 0.        , -1.        ,  1.        ,  0.        ],
       [ 1.        ,  5.        , -4.        , -2.        ],
       [-1.        , -2.        ,  2.        ,  1.        ],
       [ 0.33333333,  0.        , -0.33333333,  0.33333333]])

In [5]:
#Agar teskari matritsani asl matritsaga ko'paytirganimizda 1 lik matritsa chiqsa unda to'gri bo'ladi
np.around(inverse @ np_0,2) 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])