# Ndarray ustida amallar
* np array vektorni ishlaydi yani ichiga tasir qiladi

**`Numpy kutubxonasini chaqirib olamiz`**

In [1]:
import numpy as np

In [2]:
np_2 = np.array([1,2,3,4,5,6,7,8])

In [3]:
np_2 * 5

array([ 5, 10, 15, 20, 25, 30, 35, 40])

In [4]:
np_2 / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [5]:
np_2 + 12

array([13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
np_2 - 9

array([-8, -7, -6, -5, -4, -3, -2, -1])

In [7]:
np_2 % 5

array([1, 2, 3, 4, 0, 1, 2, 3], dtype=int32)

In [8]:
np_2 // 7

array([0, 0, 0, 0, 0, 0, 1, 1], dtype=int32)

In [9]:
np_2 == 5

array([False, False, False, False,  True, False, False, False])

In [10]:
np_2 ** 5

array([    1,    32,   243,  1024,  3125,  7776, 16807, 32768],
      dtype=int32)

## ikkita va undan ortiq matrixlar ustida amallar

In [11]:
np_3 = np.arange(4).reshape(2,2)
np_4 = np.arange(5,9).reshape(2,2)
print(np_3)
print(np_4)

[[0 1]
 [2 3]]
[[5 6]
 [7 8]]


In [12]:
np_3 - np_4

array([[-5, -5],
       [-5, -5]])

In [13]:
np_3 + np_4

array([[ 5,  7],
       [ 9, 11]])

In [14]:
np_3 * np_4

array([[ 0,  6],
       [14, 24]])

In [15]:
np_3 / np_4

array([[0.        , 0.16666667],
       [0.28571429, 0.375     ]])

In [16]:
np_3 // np_4

array([[0, 0],
       [0, 0]])

In [17]:
np_3 % np_4

array([[0, 1],
       [2, 3]])

In [18]:
np_3 ** np_4

array([[   0,    1],
       [ 128, 6561]])

In [19]:
np_5 = np.array([1,2])
print("np_4",np_4)
print("np_5",np_5)

np_4 [[5 6]
 [7 8]]
np_5 [1 2]


In [20]:
np_5 - np_4

array([[-4, -4],
       [-6, -6]])

In [21]:
np_4 - np_5

array([[4, 4],
       [6, 6]])

In [22]:
np_5 = np.arange(1,10).reshape(3,3)
np_6 = np.array([1,2,3])
print("np_6",np_6)
print("np_5",np_5)

np_6 [1 2 3]
np_5 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
np_5 - np_6

array([[0, 0, 0],
       [3, 3, 3],
       [6, 6, 6]])

In [24]:
np_6 - np_5

array([[ 0,  0,  0],
       [-3, -3, -3],
       [-6, -6, -6]])

In [25]:
np_5 = np.arange(1,7).reshape(3,2)
print("np_4",np_4)
print("np_5",np_5)

np_4 [[5 6]
 [7 8]]
np_5 [[1 2]
 [3 4]
 [5 6]]


In [26]:
np_5 - np_4

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

In [27]:
np_4 - np_5

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 