# 8/09/2022

# Numpy


# Muallif: Farrux Sotivoldiyev

# Numpy join
* `np.append(axis)` - ikkita massivni qo'shib beradi
* `np.concatenate(axis)` - ikkita massivni qo'shib beradi
* `np.vstack()` - vertikal qo'shish
* `np.hstack()` - horizontal qo'shish
* `np.dstack()` - deep yani 3-o'q bo'yicha qo'shish
* `np.stack(axis)`- bu ham qo'shib beradi
* `append` va `concatenate` bir xil funksiyalar.`vstack`,`hstack`,`dstack` shularning xususiy holi

**`Numpy kutubxonasini chaqirib olamiz`**

In [1]:
import numpy as np

In [2]:
np_2 = np.array([1,2,3,4])
np_3 = np.array([5,6,7,8])

**`np.vstack`**

In [3]:
np.vstack((np_2,np_3))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

**`np.hstack`**

In [4]:
np.hstack((np_2,np_3))

array([1, 2, 3, 4, 5, 6, 7, 8])

**`np.concatenate`**

In [5]:
np.concatenate((np_2,np_3)) # 1D da hstack bilan ekvivalent

array([1, 2, 3, 4, 5, 6, 7, 8])

**`np.append`**

In [6]:
np.append(np_2,np_3) # 1D da hstack bilan ekvivalent

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
np_4 = np.random.randint(1,5,size=(3,3))
np_5 = np.random.randint(5,9,size=(3,3))

In [8]:
np_4

array([[2, 1, 2],
       [4, 1, 3],
       [2, 3, 2]])

In [9]:
np_5

array([[8, 8, 8],
       [8, 6, 7],
       [5, 8, 8]])

In [10]:
np.vstack((np_4,np_5))

array([[2, 1, 2],
       [4, 1, 3],
       [2, 3, 2],
       [8, 8, 8],
       [8, 6, 7],
       [5, 8, 8]])

In [11]:
np.hstack((np_4,np_5))

array([[2, 1, 2, 8, 8, 8],
       [4, 1, 3, 8, 6, 7],
       [2, 3, 2, 5, 8, 8]])

In [12]:
np.append(np_4,np_5) # 2 va undan ortiq dim larda append shunday ishlaydi yani axis yozmasak bitta list qilib qaytaradi

array([2, 1, 2, 4, 1, 3, 2, 3, 2, 8, 8, 8, 8, 6, 7, 5, 8, 8])

In [13]:
np.append(np_4,np_5,axis=0)

array([[2, 1, 2],
       [4, 1, 3],
       [2, 3, 2],
       [8, 8, 8],
       [8, 6, 7],
       [5, 8, 8]])

In [14]:
np.append(np_4,np_5,axis=1)

array([[2, 1, 2, 8, 8, 8],
       [4, 1, 3, 8, 6, 7],
       [2, 3, 2, 5, 8, 8]])

In [15]:
np_4 = np.random.randint(1,5,size=(3,1))
np_5 = np.random.randint(5,9,size=(3,3))

In [16]:
np_4

array([[1],
       [3],
       [3]])

In [17]:
np_5

array([[7, 6, 6],
       [8, 5, 8],
       [8, 8, 6]])

In [18]:
np.hstack((np_4,np_5))

array([[1, 7, 6, 6],
       [3, 8, 5, 8],
       [3, 8, 8, 6]])

In [19]:
np.vstack((np_4,np_5)) # vertikal shapelari to'g'ri kelmaydi 

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 1 and the array at index 1 has size 3

In [ ]:
np_4 = np.random.randint(1,5,size=(1,3))
np_5 = np.random.randint(5,9,size=(3,3))

In [ ]:
np_4

In [ ]:
np_5

In [21]:
np.hstack((np_4,np_5)) 

array([[1, 7, 6, 6],
       [3, 8, 5, 8],
       [3, 8, 8, 6]])

In [32]:
np.vstack((np_4,np_5)) # vertikal shapelari to'g'ri kelmaydi 

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [22]:
np_4 = np.random.randint(1,5,size=(3,2))
np_5 = np.random.randint(5,9,size=(3))

In [23]:
np_4

array([[2, 4],
       [4, 4],
       [3, 1]])

In [24]:
np_5

array([7, 5, 8])

In [25]:
x = np_5[:,None]
x

array([[7],
       [5],
       [8]])

In [26]:
np.hstack((np_4,np_5[:,None]))

array([[2, 4, 7],
       [4, 4, 5],
       [3, 1, 8]])

**`np.column_stack`**

In [27]:
np_4 = np.random.randint(1,5,size=(3,2))
np_5 = np.random.randint(5,9,size=(3))

In [28]:
np_4

array([[4, 1],
       [3, 4],
       [4, 3]])

In [29]:
np_5

array([7, 8, 8])

In [30]:
np.column_stack((np_4,np_5)) #bir biriga to'g'ri kelmasa uzi tog'irlab qo'shib beradi tepadagiga o'xshab

array([[4, 1, 7],
       [3, 4, 8],
       [4, 3, 8]])