# Numpy split
* `np.split(axis)` - Axislar bo'yicha split qilib beradi va abizatelniy nechiga bo'lishni yozish kerak
* `np.hsplit()` - gorizontal split
* `np.vsplit()` - vertikal split
* `np.dsplit()` - deep split.ndim 3 bo'lgan holatlarda 3-o'q bo'yicha bo'lib beradi
* `np.array_split()` - hohlagancha bo'lib tashlaydi xatolik qaytarmaydi

**`Numpy kutubxonasini chaqirib olamiz`**

In [1]:
import numpy as np

**`np.split()`**

In [18]:
np_1 = np.random.randint(1,5,size=(4,4))
np_1

array([[2, 1, 2, 3],
       [3, 4, 4, 1],
       [1, 3, 4, 3],
       [3, 1, 2, 4]])

In [27]:
np.split(np_1,2)

[array([[2, 1, 2, 3],
        [3, 4, 4, 1]]),
 array([[1, 3, 4, 3],
        [3, 1, 2, 4]])]

In [25]:
np.split(np_1,4)

[array([[2, 1, 2, 3]]),
 array([[3, 4, 4, 1]]),
 array([[1, 3, 4, 3]]),
 array([[3, 1, 2, 4]])]

In [28]:
np.split(np_1,2,axis=0) # y o'qini teng 2 bo'lakka bo'ldi

[array([[2, 1, 2, 3],
        [3, 4, 4, 1]]),
 array([[1, 3, 4, 3],
        [3, 1, 2, 4]])]

In [29]:
np.split(np_1,2,axis=1) # x o'qini teng 2 bo'lakka bo'ldi

[array([[2, 1],
        [3, 4],
        [1, 3],
        [3, 1]]),
 array([[2, 3],
        [4, 1],
        [4, 3],
        [2, 4]])]

**`np.hsplit()`**

In [32]:
np.hsplit(np_1,2)

[array([[2, 1],
        [3, 4],
        [1, 3],
        [3, 1]]),
 array([[2, 3],
        [4, 1],
        [4, 3],
        [2, 4]])]

**`np.vsplit()`**

In [33]:
np.vsplit(np_1,2)

[array([[2, 1, 2, 3],
        [3, 4, 4, 1]]),
 array([[1, 3, 4, 3],
        [3, 1, 2, 4]])]

**`np.array_split()`** - bu bo'lish mumkin bo'lmasa ham bo'laveradi bunga farqi yoq

In [37]:
np.array_split(np_1,3)

[array([[2, 1, 2, 3],
        [3, 4, 4, 1]]),
 array([[1, 3, 4, 3]]),
 array([[3, 1, 2, 4]])]

In [40]:
np.array_split(np_1,3,axis=1)

[array([[2, 1],
        [3, 4],
        [1, 3],
        [3, 1]]),
 array([[2],
        [4],
        [4],
        [2]]),
 array([[3],
        [1],
        [3],
        [4]])]

In [42]:
np.array_split(np_1,2,axis=0)

[array([[2, 1, 2, 3],
        [3, 4, 4, 1]]),
 array([[1, 3, 4, 3],
        [3, 1, 2, 4]])]