# 8/09/2022

# Numpy


# Muallif: Farrux Sotivoldiyev

# Numpy array yaratish
* np.array
* np.asarray
* np.arange
* np.ones
* np.ones_like
* np.zeros
* np.zeros_like
* np.full
* np.full_like
* np.empty
* np.empty_like
* np.eye
* np.identity
* np.random.(randint,rand,randn)

**`Numpy kutubxonasini chaqirib olamiz`**

In [1]:
import numpy as np

**`Xar hil pithon listlari,tuple,dict,set larini yaratib oldik`**

In [2]:
x_list = [3,4,5,11,9,2]
x_matrix_kv = [[12,3,5,4],[3,9,0,4],[4,8,6,1],[1,8,4,7]]
x_matrix3X4 = [[3,5,4,6],[3,9,0,4],[4,8,6,9]]
x_tuple = (1,5,8,0,2,3345,6778,8989,9)
x_dict = {"a":5,"b":"salom","c":7,"d":0}
x_set = {2,3,456,78,9,0,2,44,5,7,8,9,4,2}


print(type(x_list))
print(type(x_matrix_kv))
print(type(x_matrix3X4))
print(type(x_tuple))
print(type(x_dict))
print(type(x_set))

<class 'list'>
<class 'list'>
<class 'list'>
<class 'tuple'>
<class 'dict'>
<class 'set'>


**`np.array()`** - pithon dagi barcha iteratsiya obyektlarini ndarray ga o'tqazadi

In [3]:
np_list1 = np.array((1,3,46,77.89,40,9))
print(np_list1)
type(np_list1)

[ 1.    3.   46.   77.89 40.    9.  ]


numpy.ndarray

In [4]:
np_list2 = np.array(x_list)
print(np_list2)
type(np_list2)

[ 3  4  5 11  9  2]


numpy.ndarray

In [5]:
np_list3 = np.array(x_tuple)
print(np_list3)
type(np_list3)

[   1    5    8    0    2 3345 6778 8989    9]


numpy.ndarray

In [6]:
np_list4 = np.array(x_dict)
print(np_list4)
type(np_list4)

{'a': 5, 'b': 'salom', 'c': 7, 'd': 0}


numpy.ndarray

In [7]:
np_list5 = np.array(x_set)
print(np_list5)
type(np_list5)

{0, 2, 3, 4, 5, 7, 456, 9, 8, 44, 78}


numpy.ndarray

**`np.asarray()`** - pithon dagi barcha iteratsiya obyektlarini ndarray ga o'tqazadi

In [8]:
np_list6 = np.asarray(x_matrix3X4)
print(np_list6)
type(np_list6)

[[3 5 4 6]
 [3 9 0 4]
 [4 8 6 9]]


numpy.ndarray

In [9]:
np_list6 = np.asarray(x_matrix_kv)
print(np_list6)
type(np_list6)

[[12  3  5  4]
 [ 3  9  0  4]
 [ 4  8  6  1]
 [ 1  8  4  7]]


numpy.ndarray

**`np.arange()`** - pithondagi range funksiyasi bilan bir xil ishlaydi

In [10]:
x = np.arange(15)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
type(x)

numpy.ndarray

In [12]:
np_list7 = np.arange(25,100)
print(*np_list7)
type(np_list7)

25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99


numpy.ndarray

**`np.ones()`** - shape kiritsangiz shu shaplarga mos 1 lardan iborat ndarray qaytaradi

In [13]:
np_list8 = np.ones((1,2,3,4))
print(np_list8)
type(np_list8)

[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]]


numpy.ndarray

**`np.ones_like()`** - boshqa bir arrayni bersangiz uning o'lchamini olib 1 lar bilan to'ldirilgan ndarray qaytaradi 

In [14]:
np_list9 = np.ones_like(x_matrix3X4)
print(np_list9)
type(np_list9)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


numpy.ndarray

In [15]:
np_list9 = np.ones_like(x_matrix_kv)
print(np_list9)
type(np_list9)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


numpy.ndarray

**`np.zeros()`** - shape kiritsangiz shu shaplarga mos 0 lardan iborat ndarray qaytaradi

In [16]:
np_list10 = np.zeros((3,3,5))
print(np_list10)
type(np_list10)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


numpy.ndarray

**`np.zeros_like()`** - boshqa bir arrayni bersangiz uning o'lchamini olib 0 lar bilan to'ldirilgan ndarray qaytaradi

In [17]:
np_list11 = np.zeros_like(x_matrix3X4)
print(np_list11)
type(np_list11)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


numpy.ndarray

In [18]:
np_list11 = np.zeros_like(x_matrix_kv)
print(np_list11)
type(np_list11)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


numpy.ndarray

**`np.full()`** - shape va son kiritsangiz shu shaplarga mos kiritgan sonimizdan iborat ndarray qaytaradi

In [19]:
np_list12 = np.full((3,2,5),9)
print(np_list12)
type(np_list12)

[[[9 9 9 9 9]
  [9 9 9 9 9]]

 [[9 9 9 9 9]
  [9 9 9 9 9]]

 [[9 9 9 9 9]
  [9 9 9 9 9]]]


numpy.ndarray

**`np.full_like()`** - boshqa bir array va son bersangiz uning o'lchamini olib o'sha son bilan to'ldirilgan ndarray qaytaradi

In [20]:
np_list13 = np.full_like(x_matrix3X4,6)
print(np_list13)
type(np_list13)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


numpy.ndarray

**`np.empty()`** - shape kiritsangiz shu shaplarga mos bo'sh sonlar bilan to'ldirilgan ndarray qaytaradi

In [21]:
np_list14 = np.empty((3,4))
print(np_list14)
type(np_list14)

[[1.01855798e-312 1.06099790e-312 1.01855798e-312 9.54898106e-313]
 [1.18831764e-312 1.01855798e-312 1.23075756e-312 1.03977794e-312]
 [1.03977794e-312 9.76118064e-313 1.18831764e-312 1.90979621e-312]]


numpy.ndarray

**`np.empty_like()`** - boshqa bir arrayni bersangiz uning o'lchamini olib bo'sh sonlar bilan to'ldirilgan ndarray qaytaradi

In [22]:
np_list15 = np.empty_like(x_matrix_kv)
print(np_list15)
type(np_list15)

[[      0       0       0       0]
 [      0       0       0       0]
 [      0       0    1816       0]
 [      0 4980828       0 7077985]]


numpy.ndarray

**`np.eye()`** - shape kiritamiz shu shape ga mos birlik matritsa qaytaradi.(birlik matritsa - asosiy dioganali 1 lardan qolgan qismi 0 lardan iborat matritsa)

In [23]:
np_list16 = np.eye(4,5)
print(np_list16)
type(np_list16)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


numpy.ndarray

In [24]:
# shape kiritamiz shu shape ga mos birlik matritsa qaytaradi.
# (birlik matritsa - asosiy dioganali 1 lardan qolgan qismi 0 lardan iborat matritsa)
# uning 3 chi soni asosiy dioganalini tepaga yoki pastga tushishini ifodalaydi(0<x-tepaga chiqaradi,aksincha bo'lsa pastga)
np_list16 = np.eye(4,5,1)
print(np_list16)
type(np_list16)

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


numpy.ndarray

**`np.identity()`** - unga bir dona son kiritamiz shunga mos kvadrat birlik matritsa qaytaradi.(birlik matritsa - asosiy dioganali 1 lardan qolgan qismi 0 lardan iborat matritsa)

In [25]:
np_list17 = np.identity(5)
print(np_list17)
type(np_list17)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


numpy.ndarray

# np.random

* **`np.random.rand()`**
* **`np.random.randn()`**
* **`np.random.randint()`**

**`np.random.rand()`** 0 va 1 oralig'idagi sonlardan n o'lchamli massiv hosil qiladi.

In [26]:
np_1 = np.random.rand(3,4,2)
np_1

array([[[0.60429415, 0.05994753],
        [0.05757835, 0.84730661],
        [0.43843917, 0.25174063],
        [0.50919605, 0.60775493]],

       [[0.7872778 , 0.87264136],
        [0.69410514, 0.75702074],
        [0.20730848, 0.22432733],
        [0.44091258, 0.51014939]],

       [[0.61532186, 0.08705005],
        [0.78434216, 0.04682535],
        [0.20543259, 0.60630807],
        [0.75877175, 0.42805675]]])

**`np.random.randn()`** istalgan sonlardan n o'lchamli massiv hosil qilib beradi.Odatda kichikroq sonlardan tanlaydi.

In [27]:
np_1 = np.random.randn(5,2)
np_1

array([[ 0.78054717,  1.31650068],
       [ 0.49393428,  1.17185329],
       [-0.36725189, -0.65986471],
       [-0.97110108, -0.07466123],
       [-0.33720692, -1.0753797 ]])

**`np.random.randint()`** 
* 1.Ichiga yozilgan range oralig'ida istalgan sonni qaytaradi
* 2.range dan tshqari ichiga yana size ham yozish mumkin u bizga o'sha o'lchamda n o'lchamli massiv hosil qilib beradi

In [28]:
np_1 = np.random.randint(5,10)
np_1

8

In [29]:
np_1 = np.random.randint(5,10,size=(4,3,2))
np_1

array([[[8, 8],
        [5, 5],
        [6, 5]],

       [[9, 7],
        [9, 9],
        [9, 6]],

       [[6, 9],
        [9, 9],
        [6, 9]],

       [[5, 8],
        [9, 5],
        [9, 5]]])

# Qo'shimcha

* *1.*`shape` - o'lchamlarini ko'rsatadi.
* *2.*`size` - ichida nechta elementi borligini ko'rsatadi.
* *3.*`dtype` - toifasini ko'rsatadi.
* *4.*`ndim` - necha o'lchamli ekanini ko'rsatadi.
* *5.*`nbytes` - necha bayt joy egallaganini ko'rsatadi.

In [30]:
qoshimcha1 = np.ones((5,6,4))
qoshimcha1

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [31]:
qoshimcha1.shape

(5, 6, 4)

In [32]:
qoshimcha1.size

120

In [33]:
qoshimcha1.dtype

dtype('float64')

In [34]:
qoshimcha1.ndim

3

In [35]:
qoshimcha1.nbytes

960

In [36]:
qoshimcha1 = np.ones((5,6,4),dtype=np.uint8)

In [37]:
qoshimcha1.nbytes

120