# 8/09/2022

# Numpy


# Muallif: Farrux Sotivoldiyev

# Numpy Types
* `bool` = True,False
*
* `int8` = -128 - 127  (1 bit sign uchun 7 bit son hosil qilish uchun - Xotiradan 8 bit yani 1 bayt joy beradi)
* `int16` = -32768 - 32767
* `int32` = -2147483648 - 2147483647
* `int64` = -9223372036854775808 - 9223372036854775807
*
* `uint8` = 0 - 255   (8 bitning hammasi son hosil qilish uchun)
* `uint16` = 0 - 65536
* `uint32` = 0 - 429496729
* `uint64` = 0 - 18446744073709551615
*
* `float16` = 1 bit sign, 5 bit exponent, 10 bit mantissa
* `float32` = 1 bit sign, 8 bit exponent, 23 bit mantissa
* `float64` = 1 bit sign, 11 bit exponent, 52 bit mantissa
*
* `complex64` = float32 + float32
* `complex128` = float64 + float64
*
* `string` - bir belgi bir bayt

**`Numpy kutubxonasini chaqirib olamiz`**

In [1]:
import numpy as np

**`np.int8`** - bu yerda int8 (-128 - 127 ) oraliqda bo'lgani uchun undan katta yoki undan kichik son kiritsak o'z oralig'iga o'girib oladi.Ya'ni -130 kiritsak -128 dan kichkina bo'lgani uchun 127 dan yana qaytadi va 126 bo'lib qoladi.Agar 130 bo'lsa manfiy tarafdan qaytadi va -126 bo'lib qoladi.

In [2]:
a = np.array([-130,2,3,4,5],dtype=np.int8)
print(a)

[126   2   3   4   5]


**`np.uint8`** - bu yerda uint8 (0 - 255 ) oraliqda bo'lgani uchun undan katta yoki undan kichik son kiritsak o'z oralig'iga o'girib oladi.Ya'ni -5 kiritsak 0 dan kichkina bo'lgani uchun 255 dan yana qaytadi va 251 bo'lib qoladi.Agar 260 bo'lsa 0 tarafdan qaytadi va 4 bo'lib qoladi.

In [3]:
b = np.array([-5,2,3,4,58],dtype=np.uint8)
print(b)

[251   2   3   4  58]


In [4]:
b = np.array([260,2,3,4,58],dtype=np.uint8)
print(b)

[ 4  2  3  4 58]
