# Numpy sortlash
* x.sort() - massivni o'zini sortlab tashlaydi(sort by python)
* np.sort(x) - sortlab javob qaytaradi(sorted by python)
* *`Sort funksiyasi faqat axeslar bo'yicha ishlaydi`*

**`Numpy kutubxonasini chaqirib olamiz`**

In [2]:
import numpy as np

In [21]:
np_3 = np.random.randint(1,5,size=(3,2,3))
np_3

array([[[1, 2, 3],
        [2, 2, 4]],

       [[3, 2, 3],
        [4, 3, 2]],

       [[4, 3, 4],
        [3, 2, 1]]])

In [22]:
np_4 = np_3.copy()
np_4.sort()
np_4

array([[[1, 2, 3],
        [2, 2, 4]],

       [[2, 3, 3],
        [2, 3, 4]],

       [[3, 4, 4],
        [1, 2, 3]]])

In [23]:
np.sort(np_3) # default holati satrni ichidagi elementlari bo'yicha saralaydi

array([[[1, 2, 3],
        [2, 2, 4]],

       [[2, 3, 3],
        [2, 3, 4]],

       [[3, 4, 4],
        [1, 2, 3]]])

In [24]:
np.sort(np_3,axis=0) # element turgan o'rni bo'yicha

array([[[1, 2, 3],
        [2, 2, 1]],

       [[3, 2, 3],
        [3, 2, 2]],

       [[4, 3, 4],
        [4, 3, 4]]])

In [26]:
np.sort(np_3,axis=1) #satrlarning ustunlari bo'yicha saralaydi

array([[[1, 2, 3],
        [2, 2, 4]],

       [[3, 2, 2],
        [4, 3, 3]],

       [[3, 2, 1],
        [4, 3, 4]]])