# Statistik funksiyalar
* `np.sum` - summasini chiqarib beradi.Axislar bo'yicha ham ishlaydi
* `np.mean` - o'rtacha qiymat(o'rta arifmetik)
* `np.std` - machine learning da o'rganamiz!!!
* `np.var` - machine learning da o'rganamiz!!!
* `np.cumsum` - o'zidan oldini yeg'indiga qo'shib ketaveradi(fibonachi sonlari mexanizmidek ishlaydi)
* `np.cumprod` - o'zidan oldini ko'paytmaga ko'paytirib ketaveradi
* `np.min`- minimumini topib beradi
* `np.max`- maximumini topib beradi

**`Numpy kutubxonasini chaqirib olamiz`**

In [1]:
import numpy as np

In [2]:
np_1 = np.random.randint(1,4,size=(5,5))
np_1

array([[2, 2, 3, 1, 2],
       [2, 2, 2, 1, 1],
       [2, 2, 1, 1, 1],
       [2, 3, 2, 3, 2],
       [2, 3, 3, 1, 2]])

**`np.sum`**

In [3]:
np.sum(np_1)

48

In [4]:
np_1.sum()

48

In [5]:
np.sum(np_1,axis=0) # 0 - y o'qi bo'yicha sum qiladi

array([10, 12, 11,  7,  8])

In [6]:
np.sum(np_1,axis=1) # 1 - x o'qi bo'yicha sum qiladi

array([10,  8,  7, 12, 11])

In [7]:
np_2 = np.random.randint(1,4,size=(3,2,3))
np_2

array([[[2, 3, 3],
        [2, 3, 1]],

       [[3, 2, 2],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 1]]])

In [8]:
np.ndim(np_2)

3

In [9]:
np.sum(np_2)

37

In [10]:
# axis=0  3dim da o'rni bo'yicha sum qiladi ya'ni 01+01+01+01 hamma bir xil o'rindagilarni sum qilib chiqadi
np.sum(np_2,axis=0) 

array([[6, 7, 8],
       [4, 7, 5]])

In [11]:
np.sum(np_2,axis=1) # axis=1  3dim da ustun bo'yicha sum qiladi

array([[4, 6, 4],
       [4, 4, 5],
       [2, 4, 4]])

In [12]:
np.sum(np_2,axis=2) # axis=2  3dim da satr bo'yicha sum qiladi

array([[8, 6],
       [7, 6],
       [6, 4]])

In [13]:
np_4 = np.random.randint(1,4,size=(3,4,2,3))
np_4

array([[[[2, 2, 1],
         [3, 2, 1]],

        [[3, 3, 1],
         [3, 2, 3]],

        [[2, 1, 1],
         [3, 3, 1]],

        [[2, 1, 1],
         [1, 1, 2]]],


       [[[3, 3, 2],
         [3, 3, 2]],

        [[1, 1, 1],
         [2, 3, 2]],

        [[1, 1, 3],
         [2, 3, 2]],

        [[1, 2, 2],
         [1, 1, 3]]],


       [[[3, 1, 3],
         [3, 3, 2]],

        [[3, 1, 3],
         [2, 2, 3]],

        [[3, 3, 1],
         [1, 2, 2]],

        [[3, 3, 1],
         [2, 3, 2]]]])

In [14]:
np.ndim(np_4)

4

In [15]:
np.sum(np_4)

148

In [16]:
# axis=0  4dim da o'rni bo'yicha sum qiladi ya'ni 01+01+01+01 hamma bir xil o'rindagilarni sum qilib chiqadi
np.sum(np_4,axis=0)

array([[[8, 6, 6],
        [9, 8, 5]],

       [[7, 5, 5],
        [7, 7, 8]],

       [[6, 5, 5],
        [6, 8, 5]],

       [[6, 6, 4],
        [4, 5, 7]]])

In [17]:
np.sum(np_4,axis=1) # axis=1  4dim da har bitta 3dim nining mos indexdagilari qo'shiladi

array([[[ 9,  7,  4],
        [10,  8,  7]],

       [[ 6,  7,  8],
        [ 8, 10,  9]],

       [[12,  8,  8],
        [ 8, 10,  9]]])

In [18]:
np.sum(np_4,axis=2) # axis=2  4dim da har bitta 3dimning ustunlari qo'shiladi

array([[[5, 4, 2],
        [6, 5, 4],
        [5, 4, 2],
        [3, 2, 3]],

       [[6, 6, 4],
        [3, 4, 3],
        [3, 4, 5],
        [2, 3, 5]],

       [[6, 4, 5],
        [5, 3, 6],
        [4, 5, 3],
        [5, 6, 3]]])

In [19]:
np.sum(np_4,axis=3) # axis=3  4dim da har bitta 3dimning satrlari qo'shiladi

array([[[5, 6],
        [7, 8],
        [4, 7],
        [4, 4]],

       [[8, 8],
        [3, 7],
        [5, 7],
        [5, 5]],

       [[7, 8],
        [7, 7],
        [7, 5],
        [7, 7]]])

**`np.mean`**

In [21]:
np_3 = np.random.randint(1,4,size=(2,4,3))
np_3

array([[[1, 2, 3],
        [1, 2, 1],
        [1, 2, 1],
        [3, 1, 2]],

       [[1, 2, 2],
        [1, 2, 1],
        [1, 1, 3],
        [3, 2, 1]]])

In [22]:
np.mean(np_3[:,:,2:])

1.75

In [23]:
np.mean(np_3)

1.6666666666666667

In [24]:
np.mean(np_3,axis=0)

array([[1. , 2. , 2.5],
       [1. , 2. , 1. ],
       [1. , 1.5, 2. ],
       [3. , 1.5, 1.5]])

In [25]:
np.mean(np_3,axis=1)

array([[1.5 , 1.75, 1.75],
       [1.5 , 1.75, 1.75]])

In [26]:
np.mean(np_3,axis=2)

array([[2.        , 1.33333333, 1.33333333, 2.        ],
       [1.66666667, 1.33333333, 1.66666667, 2.        ]])

**`np.cumsum`**

In [27]:
np.cumsum(np_4)

array([  2,   4,   5,   8,  10,  11,  14,  17,  18,  21,  23,  26,  28,
        29,  30,  33,  36,  37,  39,  40,  41,  42,  43,  45,  48,  51,
        53,  56,  59,  61,  62,  63,  64,  66,  69,  71,  72,  73,  76,
        78,  81,  83,  84,  86,  88,  89,  90,  93,  96,  97, 100, 103,
       106, 108, 111, 112, 115, 117, 119, 122, 125, 128, 129, 130, 132,
       134, 137, 140, 141, 143, 146, 148])

In [28]:
np.cumsum(np_3,axis=0)

array([[[1, 2, 3],
        [1, 2, 1],
        [1, 2, 1],
        [3, 1, 2]],

       [[2, 4, 5],
        [2, 4, 2],
        [2, 3, 4],
        [6, 3, 3]]])

**`np.cumprod`**

In [29]:
np_2

array([[[2, 3, 3],
        [2, 3, 1]],

       [[3, 2, 2],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 1]]])

In [30]:
np.cumprod(np_2)

array([    2,     6,    18,    36,   108,   108,   324,   648,  1296,
        1296,  2592,  7776,  7776, 15552, 46656, 46656, 93312, 93312])

In [31]:
np.cumprod(np_2,axis=0)

array([[[ 2,  3,  3],
        [ 2,  3,  1]],

       [[ 6,  6,  6],
        [ 2,  6,  3]],

       [[ 6, 12, 18],
        [ 2, 12,  3]]])

**`np.min`**

In [32]:
np_2

array([[[2, 3, 3],
        [2, 3, 1]],

       [[3, 2, 2],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 1]]])

In [33]:
np.min(np_2)

1

In [41]:
np.min(np_2,axis=0) # element turgan o'rni bo'yicha bo'yicha min oladi va yangi matrix qaytaradi

array([[1, 2, 2],
       [1, 2, 1]])

In [34]:
np.min(np_2,axis=1) # har bir yaxlit matrixni ustunlari bo'yicha min oladi va yangi matrix qaytaradi

array([[2, 3, 1],
       [1, 2, 2],
       [1, 2, 1]])

In [35]:
np.min(np_2,axis=2) # har bir yaxlit matrixni satrlari bo'yicha min oladi va yangi matrix qaytaradi

array([[2, 1],
       [2, 1],
       [1, 1]])

**`np.max`**

In [36]:
np_2

array([[[2, 3, 3],
        [2, 3, 1]],

       [[3, 2, 2],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 1]]])

In [37]:
np.max(np_2)

3

In [38]:
np.max(np_2,axis=1)

array([[2, 3, 3],
       [3, 2, 3],
       [1, 2, 3]])

In [39]:
np.max(np_2,axis=2)

array([[3, 3],
       [3, 3],
       [3, 2]])