# Universal funksiyalar

**`Numpy kutubxonasini chaqirib olamiz`**

In [1]:
import numpy as np

### Unar amallar.
* np.abs
* np.sqrt
* np.square
* np.exp
* np.log log2 log10 log1p=(log(1+x))
* np.sign
* np.ceil
* np.floor
* np.rint
* np.modf
* np.isnan
* np.cos ...

In [80]:
np_8 = np.arange(-5,11).reshape(2,2,4)
np_8

array([[[-5, -4, -3, -2],
        [-1,  0,  1,  2]],

       [[ 3,  4,  5,  6],
        [ 7,  8,  9, 10]]])

**`np.abs`** - modul

In [84]:
musbat = np.abs(np_8)
musbat

array([[[ 5,  4,  3,  2],
        [ 1,  0,  1,  2]],

       [[ 3,  4,  5,  6],
        [ 7,  8,  9, 10]]])

**`np.sqrt`** - ildiz oladi

In [85]:
np.sqrt(musbat)

array([[[2.23606798, 2.        , 1.73205081, 1.41421356],
        [1.        , 0.        , 1.        , 1.41421356]],

       [[1.73205081, 2.        , 2.23606798, 2.44948974],
        [2.64575131, 2.82842712, 3.        , 3.16227766]]])

**`np.square`** - kvadratga ko'taradi

In [86]:
np.square(np_8)

array([[[ 25,  16,   9,   4],
        [  1,   0,   1,   4]],

       [[  9,  16,  25,  36],
        [ 49,  64,  81, 100]]])

**`np.exp`** - e ni shu darajalarga ko'taradi

In [87]:
np.exp(np_8)

array([[[6.73794700e-03, 1.83156389e-02, 4.97870684e-02, 1.35335283e-01],
        [3.67879441e-01, 1.00000000e+00, 2.71828183e+00, 7.38905610e+00]],

       [[2.00855369e+01, 5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
        [1.09663316e+03, 2.98095799e+03, 8.10308393e+03, 2.20264658e+04]]])

* log ni ishlatishni tushunmadim

**`np.sign`** - + elementlar uchun 1 , - elementlar uchun esa -1 ni oladi va qaytaradi.Agar 0 bo'lsa o'zini qaytaradi

In [93]:
np.sign([1,2,-7,5,-2,1,9,-1])

array([ 1,  1, -1,  1, -1,  1,  1, -1])

In [94]:
np.sign([1,0,-7,5,-2,1,9,0])

array([ 1,  0, -1,  1, -1,  1,  1,  0])

In [103]:
np_9 = np.random.randn(3,3)
np_9

array([[ 0.38635589,  0.72134181, -0.59142736],
       [ 1.22037818, -0.60914217, -0.20435565],
       [-1.67257647,  0.78446739, -1.38707641]])

**`np.ceil`** - yuqoriga nisbatan yaxlitlash

In [104]:
np.ceil(np_9)

array([[ 1.,  1., -0.],
       [ 2., -0., -0.],
       [-1.,  1., -1.]])

**`np.floor`** - pastga nisbatan yaxlitlash

In [105]:
np.floor(np_9)

array([[ 0.,  0., -1.],
       [ 1., -1., -1.],
       [-2.,  0., -2.]])

**`np.rint`** - to'g'ri yaxlitlash

In [106]:
np.rint(np_9)

array([[ 0.,  1., -1.],
       [ 1., -1., -0.],
       [-2.,  1., -1.]])

**`np.modf`** - qoldiq va butunga ajratadi

In [110]:
print(np_9)
print()
np.modf(np_9)

[[ 0.38635589  0.72134181 -0.59142736]
 [ 1.22037818 -0.60914217 -0.20435565]
 [-1.67257647  0.78446739 -1.38707641]]



(array([[ 0.38635589,  0.72134181, -0.59142736],
        [ 0.22037818, -0.60914217, -0.20435565],
        [-0.67257647,  0.78446739, -0.38707641]]),
 array([[ 0.,  0., -0.],
        [ 1., -0., -0.],
        [-1.,  0., -1.]]))

In [109]:
print(np_8)
print()
np.modf(np_8)

[[[-5 -4 -3 -2]
  [-1  0  1  2]]

 [[ 3  4  5  6]
  [ 7  8  9 10]]]



(array([[[-0., -0., -0., -0.],
         [-0.,  0.,  0.,  0.]],
 
        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]]]),
 array([[[-5., -4., -3., -2.],
         [-1.,  0.,  1.,  2.]],
 
        [[ 3.,  4.,  5.,  6.],
         [ 7.,  8.,  9., 10.]]]))

In [121]:
np_10 = np.array([[[-5 ,-4 ,None,-2],[-1  ,0  ,1  ,2]],[[ 3  ,4  ,5 ,6],[ 7  ,8  ,9 ,10]]])
np_10

array([[[-5, -4, None, -2],
        [-1, 0, 1, 2]],

       [[3, 4, 5, 6],
        [7, 8, 9, 10]]], dtype=object)

In [122]:
np.isnan(np_10)

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

### Binar amallar.
* np.add ` + `
* np.substract` - `
* np.multiply `*`
* np.divide `/`
* np.maximum `solishtirib kattalarini yeg'adi`
* np.minimum `solishtirib kichiklarini yeg'adi`
* np.power `darajaga kotaradi`
* np.lcm `EKUK`
* np.gcd `EKUB`
* np.dot `*` `1 va 2 diminsionlar uchun. Bu method katta diminsionlar da xato ishlaydi`
* np.matmul @ `*` `3 va undan katta diminsionlar uchun`
* <,>,>=,<=,==,!=
* & | ^

In [123]:
np_11 = np.array([1,2,3,4,5])
np_12 = np.array([6,7,8,9,10])

**`np.add or +`** - nd massivlarni mos elementlarini bir biriga qo'shadi.

In [124]:
np_11 + np_12

array([ 7,  9, 11, 13, 15])

In [126]:
np.add(np_11,np_12)

array([ 7,  9, 11, 13, 15])

**`np.subtract or -`** - nd massivlarni mos elementlarini bir biridan ayiradi.

In [127]:
np_11 - np_12

array([-5, -5, -5, -5, -5])

In [128]:
np.subtract(np_11,np_12)

array([-5, -5, -5, -5, -5])

**`np.multiply or *`** - nd massivlarni mos elementlarini bir biriga ko'paytiradi.

In [129]:
np_11 * np_12

array([ 6, 14, 24, 36, 50])

In [130]:
np.multiply(np_11,np_12)

array([ 6, 14, 24, 36, 50])

**`np.divide or /`** - nd massivlarni mos elementlarini bir biriga bo'ladi.

In [131]:
np_11 / np_12

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [133]:
np.divide(np_11,np_12)

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [138]:
np_13 = np.array([2,5,3,8,5])
np_14 = np.array([3,7,8,9,10])

**`np.maximum`** - nd massivlarni mos elementlarini kattalarini oladi.(np.max)-dan farqli ishlaydi 

In [140]:
np.maximum(np_13,np_14)

array([ 3,  7,  8,  9, 10])

**`np.minimum`** - nd massivlarni mos elementlarini kichiklarini oladi.(np.min)-dan farqli ishlaydi 

In [141]:
np.minimum(np_13,np_14)

array([2, 5, 3, 8, 5])

**`np.power`** - nd massivlarni mos elementlari bo'yicha darajaga ko'taradi.

In [142]:
np.power(np_13,np_14)

array([        8,     78125,      6561, 134217728,   9765625])

**`np.lcm`** - nd massivlarni mos elementlarini EKUK ni oladi.

In [143]:
np.lcm(np_13,np_14)

array([ 6, 35, 24, 72, 10])

**`np.gcd`** - nd massivlarni mos elementlarini EKUB ni oladi.

In [144]:
np.gcd(np_13,np_14)

array([1, 1, 1, 1, 5])

**`np.dot`**

*1d array ustida amal*

In [145]:
np.dot(np_13,np_14)

187

*2d array ustida amal*

In [146]:
np_13 = np.array([2,5,3,8]).reshape(2,2)
np_14 = np.array([3,7,8,9]).reshape(2,2)
print(np_13)
print(np_14)

[[2 5]
 [3 8]]
[[3 7]
 [8 9]]


In [147]:
np.dot(np_13,np_14)

array([[46, 59],
       [73, 93]])

*1d va 2d array ustida amal*

In [148]:
np_13 = np.array([2,5])
np_14 = np.array([3,7,8,9]).reshape(2,2)
print(np_13)
print(np_14)

[2 5]
[[3 7]
 [8 9]]


In [149]:
np.dot(np_13,np_14)

array([46, 59])

*3d array ustida amal*

In [157]:
np_13 = np.arange(1,28).reshape(3,3,3)
np_14 = np.arange(28,55).reshape(3,3,3)
print(np_13)
print("----------------")
print(np_14)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
----------------
[[[28 29 30]
  [31 32 33]
  [34 35 36]]

 [[37 38 39]
  [40 41 42]
  [43 44 45]]

 [[46 47 48]
  [49 50 51]
  [52 53 54]]]


In [159]:
np.dot(np_13,np_14)    # np.dot 3d va undan yuqori massivlarda xato ishlashni boshlaydi yani quidagiday:

array([[[[ 192,  198,  204],
         [ 246,  252,  258],
         [ 300,  306,  312]],

        [[ 471,  486,  501],
         [ 606,  621,  636],
         [ 741,  756,  771]],

        [[ 750,  774,  798],
         [ 966,  990, 1014],
         [1182, 1206, 1230]]],


       [[[1029, 1062, 1095],
         [1326, 1359, 1392],
         [1623, 1656, 1689]],

        [[1308, 1350, 1392],
         [1686, 1728, 1770],
         [2064, 2106, 2148]],

        [[1587, 1638, 1689],
         [2046, 2097, 2148],
         [2505, 2556, 2607]]],


       [[[1866, 1926, 1986],
         [2406, 2466, 2526],
         [2946, 3006, 3066]],

        [[2145, 2214, 2283],
         [2766, 2835, 2904],
         [3387, 3456, 3525]],

        [[2424, 2502, 2580],
         [3126, 3204, 3282],
         [3828, 3906, 3984]]]])

**`np.matmul`** **`@`**

In [160]:
np.matmul(np_13,np_14)    # matmul,@ - katta diminsionlar uchun yani 3 va undan ortiq

array([[[ 192,  198,  204],
        [ 471,  486,  501],
        [ 750,  774,  798]],

       [[1326, 1359, 1392],
        [1686, 1728, 1770],
        [2046, 2097, 2148]],

       [[2946, 3006, 3066],
        [3387, 3456, 3525],
        [3828, 3906, 3984]]])

In [161]:
np_13 @ np_14

array([[[ 192,  198,  204],
        [ 471,  486,  501],
        [ 750,  774,  798]],

       [[1326, 1359, 1392],
        [1686, 1728, 1770],
        [2046, 2097, 2148]],

       [[2946, 3006, 3066],
        [3387, 3456, 3525],
        [3828, 3906, 3984]]])